### ISSUE TITLE
Track meta data tagging 

### ISSUE THREAD

**Issue by Hansbacktin** [DevYukine/red_oxide#12]
I will be honest I do not know much of anything about coding. If it were not for a ton of googling I do not think I would have go this code to work at all, but after hours of trying ( yeaaa go me) I actually got it to work which was dope. wanna go ahead and say thanks for the hard work you put into this software I really do appreciate you.

My only issue was every time I transcoded a file I noticed the tagging was incorrect. It seems to always list each track as part of another disk. The disk number is always the number of the corresponding track.

I do not know if its just me being a noob or if it is something that has just gone over looked but I wanted to bring it to your attention.

Other than that everything else works like a charm for me! A little bit more info I am using windows 10 used both the pre compiled exe's and ran the build cargo build function in power shell to compile an exe. I had all the prerequisite programs added to path too.

Thanks again in advance let me know if I am just being a goober or if you need anymore info.

**Comment by DevYukine** [comment]
Hey,

this is sadly related to the audiotags library i used for converting tags from FLAC files to tags for MP3 files (FLAC24 -> FLAC transcodes keep all tags), I've upgraded the audiotags library (1e105877a27542e1ff600e686f5dc3cd60cf3c55) which should fix that issue 👍 

If you find another issue with tags feel free to open another issue.
