### ISSUE TITLE
Can't get it past 'Logged in as X on the Redacted API'

### ISSUE THREAD

**Issue by miczlo** [DevYukine/red_oxide#13]
Running on Windows, installed dependencies
Trying to run it with --config-file=config.json -d --debug
All I get is  a green tick next to Logged in as X and then it exits, no error no debug, nothing to go with
Tried feeding parameters rather than config file but same result
Any ideas?

**Comment by DevYukine** [comment]
Did you add any Permalinks after the command in the CLI? by default it won't do anything without adding arguments to the transcode command.

**Comment by gravelfreeman** [comment]
I'm facing the same behaviour which makes me question myself that I may not understand the purpose of this tool. I'm running the command

`red_oxide transcode --debug -d -c /etc/red_oxide/red_oxide.config.json`

Which returns no errors and the following confirmation

`[✅] Logged in as *** on the Redacted API`

My expectation is that red_oxide would scan my library files in the path declared in my config file

`"content_directory": "/mnt/music",`

And then try to find these Artist - Album on Redacted and if it's not there upload it and if it's already there but not all formats, upload the missing formats.

I'm confused what this tool is for. If I need to manually enter the permalink of all my torrents one by one, it's gonna take me ages and will most likely defy the point of automating uploading.
