### ISSUE TITLE
Unable to use. This error persists,

### ISSUE THREAD

**Issue by Hunerk** [DevYukine/red_oxide#3]
Error: Redacted API returned an error while uploading a torrent: <html>
<head><title>500 Internal Server Error</title></head>
<body>
<center><h1>500 Internal Server Error</h1></center>
<hr><center>nginx</center>
</body>
</html>

**Comment by DevYukine** [comment]
This error is on REDacteds site and nothing i can do about, this likely happened when they had downtime and api issues on there side
