### ISSUE TITLE
Invalid characters on folder names

### ISSUE THREAD

**Issue by boredness** [DevYukine/red_oxide#4]
I've encountered this on two ocasions:
`Error: Redacted API returned an error while uploading a torrent: {"status":"failure","error":"The file or folder in the torrent that has the name 'Big | Brave - Nature Morte [2023] (CD - MP3 - 320)' contains the forbidden character '|'. Please recheck all files and folders in the directory and rename them as necessary and recreate the torrent.<br \/><br \/>\nNote: The complete list of characters that are disallowed are shown below:<br \/>\n\t\t : ? < > \\ * | \" \/\/ (Leading Space)"}`

`Error: Redacted API returned an error while uploading a torrent: {"status":"failure","error":"The file or folder in the torrent that has the name 'Therapy? - Hard Cold Fire [2023] (CD - MP3 - V0)' contains the forbidden character '?'. Please recheck all files and folders in the directory and rename them as necessary and recreate the torrent.<br \/><br \/>\nNote: The complete list of characters that are disallowed are shown below:<br \/>\n\t\t : ? < > \\ * | \" \/\/ (Leading Space)"}`

Can you add for it to automatically replace those either just remove them completely or add an underscore (_) like they do on site.

Thank you.

**Comment by DevYukine** [comment]
i'll add an option to ignore such characters, thanks for letting me know :)

**Comment by DevYukine** [comment]
Fixed in #6
