### ISSUE TITLE
Unable to start.

### ISSUE THREAD

**Issue by axiommer** [DevYukine/red_oxide#5]
[✅] Logged in as xxxx on the Redacted API
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:177:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by DevYukine** [comment]
I've added error logs for this issue in specific in commit d92aa0b40598d418cb41ad9c3e355d21ec4fd7f2, your URL is invalid and can't be parsed, make sure to wrap PLs in quotes as those contain the & character which is interpreted by your terminal otherwise

**Comment by SavageCore** [comment]
This probably shouldn't be closed. PLs now take the form: `https://redacted.ch/torrents.php?torrentid=xx`
